
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



wdashboard = Tk()

wdashboard.title('Dashboard')
wdashboard.geometry("1045x600")
wdashboard.configure(bg = "#F4F5F9")

width_of_window = 1045
height_of_window = 600
screen_width = wdashboard.winfo_screenwidth()
screen_height = wdashboard.winfo_screenheight()
x_coordinate = (screen_width/2)-(width_of_window/2)
y_coordinate = (screen_height/2)-(height_of_window/2)
wdashboard.geometry("%dx%d+%d+%d" %(width_of_window,height_of_window,x_coordinate,y_coordinate))






def opentwitter():
    wdashboard.destroy()
    import Twitter
    
def openfacebook():
    wdashboard.destroy()
    import Facebook

def openyoutube():
    wdashboard.destroy()
    import Youtube
    
canvas = Canvas(
    wdashboard,
    bg = "#F4F5F9",
    height = 600,
    width = 1045,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_welcome = PhotoImage(
    file=relative_to_assets("image_welcome.png"))
image_welcome = canvas.create_image(
    276.0,
    104.0,
    image=image_image_welcome
)

button_image_tweet = PhotoImage(
    file=relative_to_assets("button_tweet.png"))
button_tweet = Button(
    image=button_image_tweet,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [opentwitter()],
    relief="flat"
)
button_tweet.place(
    x=105.0,
    y=152.0,
    width=414.0,
    height=163.0
)

button_image_yt = PhotoImage(
    file=relative_to_assets("button_yt.png"))
button_yt = Button(
    image=button_image_yt,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [openyoutube()],
    relief="flat"
)
button_yt.place(
    x=533.0,
    y=152.0,
    width=414.0,
    height=163.0
)

button_image_fb = PhotoImage(
    file=relative_to_assets("button_fb.png"))
button_fb = Button(
    image=button_image_fb,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: [openfacebook()],
    relief="flat"
)

button_fb.place(
    x=104.0,
    y=327.0,
    width=415.0,
    height=163.0
)


wdashboard.resizable(False, False)
wdashboard.mainloop()
