
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter.ttk import Progressbar
from tkinter import ttk
from tkinter import HORIZONTAL
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1045x600")
window.configure(bg = "#FFFFFF")


width_of_window = 1045
height_of_window = 600
screen_width = window.winfo_screenwidth()
screen_height = window.winfo_screenheight()
x_coordinate = (screen_width/2)-(width_of_window/2)
y_coordinate = (screen_height/2)-(height_of_window/2)
window.geometry("%dx%d+%d+%d" %(width_of_window,height_of_window,x_coordinate,y_coordinate))

window.overrideredirect(1)



a='#249794'

def new_win():
    window.destroy()
    import Dashboard
    


#splash screen timer
window.after(3000, new_win)

   

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 1045,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_bg = PhotoImage(
    file=relative_to_assets("image_bg.png"))
image_bg = canvas.create_image(
    522.0,
    300.0,
    image=image_image_bg
)

canvas.create_text(
    203.0,
    398.0,
    anchor="nw",
    text="A system capable of determining the sentiment of netizens in various",
    fill="#C2C2C2",
    font=("Roboto", 20 * -1)
)

canvas.create_text(
    277.0,
    423.0,
    anchor="nw",
    text="social networking platforms about a certain topic.",
    fill="#C2C2C2",
    font=("Roboto", 20 * -1)
)

canvas.create_text(
    398.0,
    96.0,
    anchor="nw",
    text="WELCOME TO",
    fill="#FFFFFF",
    font=("RobotoRoman Medium", 30 * -1)
)


window.resizable(False, False)
window.mainloop()
